name: Clang Auto Format Code On Main Repo

on:
  push:
    branches:
      - master
      - dev

jobs:
  auto-formatter-on-main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: DoozyX/clang-format-lint-action@v0.15
      with:
        source: "./code"
        extensions: 'h,cpp'
        clangFormatVersion: 14
        style: file
        inplace: True

    - uses: EndBug/add-and-commit@v9.1.1
      with:
        committer_name: GitHub Actions
        committer_email: 41898282+github-actions[bot]@users.noreply.github.com
        message: 'Clang-format changes exist. Committing.'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}